version: '3.8'

services:
  threads_redis:
    container_name: threads_redis
    image: redis:alpine
    expose:
      - 6379
    ports:
      - 6379:6379 # Public port để lát nữa test multiple worker
    restart: unless-stopped
  threads_redis_commander:
    container_name: threads_redis_commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8088:8081'
    depends_on:
      - threads_redis