version: '3'
services:
  threads_redis:
    image: redis:latest
    container_name: threads_redis
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - redis
networks:
  redis:
    driver: bridge
